### ISSUE TITLE
兼容新py版本时 需要升级依赖的marshmallow

### ISSUE THREAD

**Issue by jokester** [kozzzx/flask-apikit#2]
我在试图给萌翻backend升级python时发现以下问题

- 要在较新的python跑 至少需要 https://github.com/marshmallow-code/marshmallow/blob/dev/CHANGELOG.rst#300b15-2018-09-18
- 不改下游代码最多能升级到 https://github.com/marshmallow-code/marshmallow/blob/dev/CHANGELOG.rst#300b20-2018-11-01 , 因为下个版本开始ValidatorError需要是个dict (我不是很确定). 更新的版本配合萌翻backend现在代码会有这样的异常:

```
moeflow-deploy-moeflow-backend-1         | Traceback (most recent call last):
moeflow-deploy-moeflow-backend-1         |   File "/usr/local/lib/python3.10/site-packages/marshmallow/schema.py", line 722, in _run_validator
moeflow-deploy-moeflow-backend-1         |     validator_func(output, partial=partial, many=many)
moeflow-deploy-moeflow-backend-1         |   File "/app/app/validators/auth.py", line 62, in verify_captcha_and_password
moeflow-deploy-moeflow-backend-1         |     captcha_validator(data["captcha_info"], data["captcha"])
moeflow-deploy-moeflow-backend-1         |   File "/app/app/validators/v_code.py", line 43, in captcha_validator
moeflow-deploy-moeflow-backend-1         |     raise ValidationError(e.message, [field_name])
moeflow-deploy-moeflow-backend-1         | marshmallow.exceptions.ValidationError: 验证码失效，请重新获取moeflow-deploy-moeflow-backend-1         | 
moeflow-deploy-moeflow-backend-1         | During handling of the above exception, another exception occurred:
moeflow-deploy-moeflow-backend-1         | 
moeflow-deploy-moeflow-backend-1         | Traceback (most recent call last):
moeflow-deploy-moeflow-backend-1         |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2446, in wsgi_app
moeflow-deploy-moeflow-backend-1         |     response = self.full_dispatch_request()
moeflow-deploy-moeflow-backend-1         |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1951, in full_dispatch_request
moeflow-deploy-moeflow-backend-1         |     rv = self.handle_user_exception(e)
moeflow-deploy-moeflow-backend-1         |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in handle_user_exception
moeflow-deploy-moeflow-backend-1         |     reraise(exc_type, exc_value, tb)
moeflow-deploy-moeflow-backend-1         |   File "/usr/local/lib/python3.10/site-packages/flask/_compat.py", line 39, in reraise
moeflow-deploy-moeflow-backend-1         |     raise value
moeflow-deploy-moeflow-backend-1         |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1949, in full_dispatch_request
moeflow-deploy-moeflow-backend-1         |     rv = self.dispatch_request()
moeflow-deploy-moeflow-backend-1         |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1935, in dispatch_request
moeflow-deploy-moeflow-backend-1         |     return self.view_functions[rule.endpoint](**req.view_args)
moeflow-deploy-moeflow-backend-1         |   File "/usr/local/lib/python3.10/site-packages/flask_apikit/decorators.py", line 41, in wrapper
moeflow-deploy-moeflow-backend-1         |     resp = make_response(func(*args, **kwargs))
moeflow-deploy-moeflow-backend-1         |   File "/usr/local/lib/python3.10/site-packages/flask_apikit/decorators.py", line 104, in wrapper
moeflow-deploy-moeflow-backend-1         |     resp = func(*args, **kwargs)
moeflow-deploy-moeflow-backend-1         |   File "/usr/local/lib/python3.10/site-packages/flask/views.py", line 89, in view
moeflow-deploy-moeflow-backend-1         |     return self.dispatch_request(*args, **kwargs)
moeflow-deploy-moeflow-backend-1         |   File "/usr/local/lib/python3.10/site-packages/flask/views.py", line 163, in dispatch_request
moeflow-deploy-moeflow-backend-1         |     return meth(*args, **kwargs)
moeflow-deploy-moeflow-backend-1         |   File "/app/app/apis/me.py", line 64, in post
moeflow-deploy-moeflow-backend-1         |     data = self.get_json(LoginSchema())
moeflow-deploy-moeflow-backend-1         |   File "/usr/local/lib/python3.10/site-packages/flask_apikit/views.py", line 72, in get_json
moeflow-deploy-moeflow-backend-1         |     data = self.verify_data(json_data, schema, context)
moeflow-deploy-moeflow-backend-1         |   File "/usr/local/lib/python3.10/site-packages/flask_apikit/views.py", line 30, in verify_data
moeflow-deploy-moeflow-backend-1         |     data = schema.load(data)
moeflow-deploy-moeflow-backend-1         |   File "/usr/local/lib/python3.10/site-packages/marshmallow/schema.py", line 677, in load
moeflow-deploy-moeflow-backend-1         |     return self._do_load(
moeflow-deploy-moeflow-backend-1         |   File "/usr/local/lib/python3.10/site-packages/marshmallow/schema.py", line 812, in _do_load
moeflow-deploy-moeflow-backend-1         |     self._invoke_schema_validators(
moeflow-deploy-moeflow-backend-1         |   File "/usr/local/lib/python3.10/site-packages/marshmallow/schema.py", line 1106, in _invoke_schema_validators
moeflow-deploy-moeflow-backend-1         |     self._run_validator(
moeflow-deploy-moeflow-backend-1         |   File "/usr/local/lib/python3.10/site-packages/marshmallow/schema.py", line 724, in _run_validator
moeflow-deploy-moeflow-backend-1         |     error_store.store_error(err.messages, err.field_name, index=index)
moeflow-deploy-moeflow-backend-1         |   File "/usr/local/lib/python3.10/site-packages/marshmallow/error_store.py", line 22, in store_error
moeflow-deploy-moeflow-backend-1         |     messages = {field_name: messages}
moeflow-deploy-moeflow-backend-1         | TypeError: unhashable type: 'list'

```

**Comment by jokester** [comment]
目前我本地版本是这样凑合的: https://github.com/jokester/moeflow-backend/pull/1/files

**Comment by kozzzx** [comment]
感谢已合并，并发布 0.0.7 版本
